[2022-10-23T18:19:45.669+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-23T18:19:39.302486+00:00 [queued]>
[2022-10-23T18:19:45.683+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-23T18:19:39.302486+00:00 [queued]>
[2022-10-23T18:19:45.683+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T18:19:45.684+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-23T18:19:45.685+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T18:19:45.702+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_funcionarios> on 2022-10-23 18:19:39.302486+00:00
[2022-10-23T18:19:45.707+0000] {standard_task_runner.py:54} INFO - Started process 7883 to run task
[2022-10-23T18:19:45.710+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'get_funcionarios', 'manual__2022-10-23T18:19:39.302486+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmpolpab78r']
[2022-10-23T18:19:45.712+0000] {standard_task_runner.py:83} INFO - Job 80: Subtask get_funcionarios
[2022-10-23T18:19:45.713+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-23T18:19:46.284+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-23T18:19:39.302486+00:00 [running]> on host 499050b57294
[2022-10-23T18:19:46.363+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=get_funcionarios
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T18:19:39.302486+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-23T18:19:39.302486+00:00
[2022-10-23T18:19:46.375+0000] {logging_mixin.py:117} INFO - [1, 5, 8, 4, 3, 2, 7, 6, 9]
[2022-10-23T18:19:46.376+0000] {logging_mixin.py:117} INFO - Aqui!!1!
[2022-10-23T18:19:46.376+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-10-23T18:19:46.386+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=sales_datawarehouse, task_id=get_funcionarios, execution_date=20221023T181939, start_date=20221023T181945, end_date=20221023T181946
[2022-10-23T18:19:46.446+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-23T18:19:46.469+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
