[2022-10-26T00:40:07.019+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.insert_fatoVendas manual__2022-10-26T00:39:12.695496+00:00 [queued]>
[2022-10-26T00:40:07.036+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.insert_fatoVendas manual__2022-10-26T00:39:12.695496+00:00 [queued]>
[2022-10-26T00:40:07.037+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-26T00:40:07.037+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-26T00:40:07.038+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-26T00:40:07.059+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): insert_fatoVendas> on 2022-10-26 00:39:12.695496+00:00
[2022-10-26T00:40:07.064+0000] {standard_task_runner.py:54} INFO - Started process 3790 to run task
[2022-10-26T00:40:07.069+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'insert_fatoVendas', 'manual__2022-10-26T00:39:12.695496+00:00', '--job-id', '629', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmpsvlnged3']
[2022-10-26T00:40:07.070+0000] {standard_task_runner.py:83} INFO - Job 629: Subtask insert_fatoVendas
[2022-10-26T00:40:07.072+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-26T00:40:08.008+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.insert_fatoVendas manual__2022-10-26T00:39:12.695496+00:00 [running]> on host 83cd0ab98720
[2022-10-26T00:40:08.161+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=insert_fatoVendas
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T00:39:12.695496+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-26T00:39:12.695496+00:00
[2022-10-26T00:40:08.405+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-10-26T00:40:08.422+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=sales_datawarehouse, task_id=insert_fatoVendas, execution_date=20221026T003912, start_date=20221026T004007, end_date=20221026T004008
[2022-10-26T00:40:08.490+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-26T00:40:08.520+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
