[2022-10-23T22:03:01.535+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T21:26:22.901909+00:00 [queued]>
[2022-10-23T22:03:01.557+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T21:26:22.901909+00:00 [queued]>
[2022-10-23T22:03:01.558+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T22:03:01.559+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 5
[2022-10-23T22:03:01.559+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T22:03:01.584+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_vendas> on 2022-10-23 21:26:22.901909+00:00
[2022-10-23T22:03:01.592+0000] {standard_task_runner.py:54} INFO - Started process 3517 to run task
[2022-10-23T22:03:01.598+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'get_vendas', 'manual__2022-10-23T21:26:22.901909+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmp2hlog8ov']
[2022-10-23T22:03:01.600+0000] {standard_task_runner.py:83} INFO - Job 202: Subtask get_vendas
[2022-10-23T22:03:01.601+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-23T22:03:02.767+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T21:26:22.901909+00:00 [running]> on host 83cd0ab98720
[2022-10-23T22:03:02.955+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=get_vendas
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T21:26:22.901909+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-23T21:26:22.901909+00:00
[2022-10-23T22:03:02.979+0000] {base.py:71} INFO - Using connection ID 'banco_vendas' for task execution.
[2022-10-23T22:03:05.059+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-10-23T22:03:05.074+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=sales_datawarehouse, task_id=get_vendas, execution_date=20221023T212622, start_date=20221023T220301, end_date=20221023T220305
[2022-10-23T22:03:05.147+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-23T22:03:05.194+0000] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
