[2022-10-24T20:13:01.029+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-24T19:46:43.643528+00:00 [queued]>
[2022-10-24T20:13:01.066+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-24T19:46:43.643528+00:00 [queued]>
[2022-10-24T20:13:01.067+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-24T20:13:01.068+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2022-10-24T20:13:01.069+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-24T20:13:01.119+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_funcionarios> on 2022-10-24 19:46:43.643528+00:00
[2022-10-24T20:13:01.143+0000] {standard_task_runner.py:54} INFO - Started process 16777 to run task
[2022-10-24T20:13:01.151+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'get_funcionarios', 'manual__2022-10-24T19:46:43.643528+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmp8s0z6s59']
[2022-10-24T20:13:01.156+0000] {standard_task_runner.py:83} INFO - Job 293: Subtask get_funcionarios
[2022-10-24T20:13:01.160+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-24T20:13:03.476+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.get_funcionarios manual__2022-10-24T19:46:43.643528+00:00 [running]> on host 83cd0ab98720
[2022-10-24T20:13:03.851+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=get_funcionarios
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T19:46:43.643528+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-24T19:46:43.643528+00:00
[2022-10-24T20:13:26.555+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-10-24T20:13:26.568+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=sales_datawarehouse, task_id=get_funcionarios, execution_date=20221024T194643, start_date=20221024T201301, end_date=20221024T201326
[2022-10-24T20:13:26.592+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-24T20:13:26.619+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
